### ISSUE TITLE
加controlNet后，容易出错。一模一样的生成配置，有时能用有时又不能用

### ISSUE THREAD

**Issue by Hulkhao** [Nuullll/sd-webui-ipex-enhancement#3]
驱动程序版本：31.0.101.5382
使用controlNet 
Module: depth_zoe, Model: t2i-adapter_diffusers_xl_depth_zoe
很神奇，有时能用，有时不能用。

控制台反馈如下
```
Traceback (most recent call last):
  File "D:\AIGC\Ultra-SD-v2.2\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\AIGC\Ultra-SD-v2.2\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\AIGC\Ultra-SD-v2.2\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\AIGC\Ultra-SD-v2.2\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\AIGC\Ultra-SD-v2.2\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\AIGC\Ultra-SD-v2.2\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\AIGC\Ultra-SD-v2.2\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\AIGC\Ultra-SD-v2.2\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 1015, in run_annotator
    result, is_image = preprocessor(
  File "D:\AIGC\Ultra-SD-v2.2\extensions\sd-webui-controlnet\scripts\utils.py", line 81, in decorated_func
    return cached_func(*args, **kwargs)
  File "D:\AIGC\Ultra-SD-v2.2\extensions\sd-webui-controlnet\scripts\utils.py", line 65, in cached_func
    return func(*args, **kwargs)
  File "D:\AIGC\Ultra-SD-v2.2\extensions\sd-webui-controlnet\scripts\global_state.py", line 37, in unified_preprocessor
    return preprocessor_modules[preprocessor_name](*args, **kwargs)
  File "D:\AIGC\Ultra-SD-v2.2\extensions\sd-webui-controlnet\scripts\processor.py", line 558, in zoe_depth
    result = model_zoe_depth(img)
  File "D:\AIGC\Ultra-SD-v2.2\extensions\sd-webui-controlnet\annotator\zoe\__init__.py", line 38, in __call__
    self.load_model()
  File "D:\AIGC\Ultra-SD-v2.2\extensions\sd-webui-controlnet\annotator\zoe\__init__.py", line 30, in load_model
    self.model = model.to(self.device)
  File "D:\AIGC\Ultra-SD-v2.2\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\depth_model.py", line 42, in to
    return super().to(device)
  File "D:\AIGC\Ultra-SD-v2.2\python\lib\site-packages\torch\nn\modules\module.py", line 1160, in to
    return self._apply(convert)
  File "D:\AIGC\Ultra-SD-v2.2\python\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "D:\AIGC\Ultra-SD-v2.2\python\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "D:\AIGC\Ultra-SD-v2.2\python\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  [Previous line repeated 5 more times]
  File "D:\AIGC\Ultra-SD-v2.2\python\lib\site-packages\torch\nn\modules\module.py", line 833, in _apply
    param_applied = fn(param)
  File "D:\AIGC\Ultra-SD-v2.2\python\lib\site-packages\torch\nn\modules\module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: Native API failed. Native API returns: -999 (Unknown PI error) -999 (Unknown PI error)
```

**Comment by Nuullll** [comment]
应该是爆显存，没什么办法
